/* Auto-generated by tools/sync_symbols.py — do not edit.
 * Source: symbols.toml (Tenchu Stealth Assassins)
 * Progressive symbols: discover → label → manipulate via PSX_FN_*.
 */
#pragma once

/* guessed: SYSTEM.CNF / EXE entry PC (probe seed) */
#define PSX_FN_BootEntry 0x8001A578u
#define func_8001A578 BootEntry  /* alias */
